### ISSUE TITLE
pip install pyPMClient does not work on linux

### ISSUE THREAD

**Issue by suresh-n** [paytmmoney/pyPMClient#12]
pip install pyPMClient                                     1   master 
ERROR: Could not find a version that satisfies the requirement pyPMClient (from versions: none)
ERROR: No matching distribution found for pyPMClient

**Comment by shivkumr-code** [comment]
this is not available in pip yet. you can download/clone the repository to your base location and you can import the pmclient like this.

`from pmClient.pmClient import PMClient`

**Comment by suresh-n** [comment]
thanks i will try that.

**Comment by sachinyadav10** [comment]
This is not on pip yet, you have to clone the repo. Read me is updated.

[Read Me](https://github.com/paytmmoney/pyPMClient/blob/master/README.md)
