### ISSUE TITLE
Cannot import candlestick data

### ISSUE THREAD

**Issue by shivkumr-code** [paytmmoney/pyPMClient#13]
I am able to authenticate using the API. However, cannot download options candlestick data. It didn't work. Also, there is not much documentation that explains the parameters in detail. Can you point me in the right direction? Below is the code I have currently. But I am getting a "bad request" error.

```
pm.price_chart_sym(cont='false',exchange='NSE',expiry='2023-02-23',from_date='2023-02-16',inst_type='OPTIDX',interval='MINUTE',symbol='BANKNIFTY-Feb2023-40900-PE',
to_date='2023-02-20')
```
Below is the error message. 
`AttributeError: {"status":400,"message":"Bad Request","error_code":"PM_OPEN_API_400"}`

**Comment by sachinyadav10** [comment]
Hi @shivkumr-code 
We haven’t launched Historical data and technical data yet. We will keep you posted once we launch.
