### ISSUE TITLE
pm.order_book() does not return all orders

### ISSUE THREAD

**Issue by aKummur** [paytmmoney/pyPMClient#18]
This is my code -

orders = pm.order_book()
>for o in orders['data']:
>>print("{} {}".format(o['display_name'], o['display_status']))

The output I got (only 2 orders )-

BANKNIFTY 16 MAR 38700 CALL Successful
BANKNIFTY 16 MAR 39700 CALL Rejected

My actual order book of the day(total 15 orders) -
![image](https://user-images.githubusercontent.com/16605985/225566318-2fdbb14c-60e3-4e8a-90c3-f2ef935c2fa8.png)

What is wrong here ?

**Comment by aKummur** [comment]
Any update on this?

**Comment by ravi-paytm** [comment]
Use pm.orders(), get orders from all channels
