### ISSUE TITLE
Live Market Data Not Working

### ISSUE THREAD

**Issue by knandini24x7** [paytmmoney/pyPMClient#24]
I am trying to fetch live market data for equity but preference is not working... I am trying to do this way... please correct me if I am doing wrong....

pm.get_live_market_data('LTP', ['BSE', '523144', 'EQUITY'])

it returns the response....

{'data': [{'found': False, 'message': 'You have sent preference packet in an invalid format: BSE'}, {'found': False, 'message': 'You have sent preference packet in an invalid format: 523144'}, {'found': False, 'message': 'You have sent preference packet in an invalid format: EQUITY'}]}

**Comment by sachinyadav10** [comment]
Hi @knandini24x7 

The pattern for preference is `<exchange>:<securityId>:<scripType>`.  For eg : In your case it will be`BSE:523144:EQUITY`.
