### ISSUE TITLE
Paytm Money REST API Documentation link

### ISSUE THREAD

**Issue by donrv** [paytmmoney/pyPMClient#7]
Hi, 
I am Building a trading bot for personal use. Can anyone provide Paytm Money REST API Documentation link?

**Comment by avijeett007** [comment]
Looking for same

**Comment by vkchauhan2020** [comment]
dear friends,
here i am sharing API doc link
https://developer.paytmmoney.com/docs/api/login/

**Comment by sachinyadav10** [comment]
Sharing the Api Doc : [API DOC](https://developer.paytmmoney.com/docs/api/logout/)
